<?php
$payments=json_decode($request['original_data']??'[]',true);$payments=is_array($payments)?$payments:[];$payment=$payments?$payments[0]:[];
$student=!empty($payment['student_id'])?$this->db->where('student_id',$payment['student_id'])->get('student')->row_array():[];
$year=get_settings('running_year');$term=get_settings('running_term');$enroll=!empty($payment['student_id'])?$this->db->where(['student_id'=>$payment['student_id'],'year'=>$year,'term'=>$term])->get('enroll')->row_array():[];
$class=!empty($enroll['class_id'])?$this->db->where('class_id',$enroll['class_id'])->get('class')->row_array():[];$section=!empty($enroll['section_id'])?$this->db->where('section_id',$enroll['section_id'])->get('section')->row_array():[];
$requester=!empty($request['requested_by'])?$this->db->where('admin_id',$request['requested_by'])->get('admin')->row_array():[];
$reviewer_id=(int)($request['approved_by']??0);$reviewer=$reviewer_id?$this->db->where('admin_id',$reviewer_id)->get('admin')->row_array():[];
$new_data=!empty($request['new_data'])?json_decode($request['new_data'],true):[];$new_data=is_array($new_data)?$new_data:[];
$total_amount=array_sum(array_map(function($p){return (float)($p['amount']??0);},$payments));$currency='₵';$status=$request['status']??'pending';
$method_map=['cash'=>'Cash','momo'=>'Mobile Money','cheque'=>'Cheque','bank'=>'Bank'];
?>
<style>
.approval-evidence{padding:18px;color:#334155}.approval-evidence-head{display:flex;align-items:flex-start;justify-content:space-between;gap:12px;margin-bottom:14px;padding-bottom:12px;border-bottom:1px solid #e2e8f0}.approval-evidence-head h3{margin:0;color:#0f172a;font-size:21px!important;font-weight:800}.approval-evidence-head p{margin:5px 0 0;color:#64748b;font-size:13px}.evidence-status{display:inline-flex;padding:6px 9px;border-radius:999px;font-size:11px;font-weight:800;text-transform:uppercase}.evidence-status.pending{background:#fffbeb;color:#b45309}.evidence-status.processing{background:#eff6ff;color:#1d4ed8}.evidence-status.approved{background:#ecfdf5;color:#047857}.evidence-status.rejected{background:#fef2f2;color:#b91c1c}.evidence-status.revoked{background:#f1f5f9;color:#475569}.evidence-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:10px;margin-bottom:12px}.evidence-card{padding:12px;border:1px solid #e2e8f0;border-radius:9px;background:#f8fafc}.evidence-label{margin-bottom:4px;color:#64748b;font-size:11px;font-weight:800;letter-spacing:.04em;text-transform:uppercase}.evidence-value{color:#0f172a;font-size:14px;font-weight:800;line-height:1.4;overflow-wrap:anywhere}.evidence-section{margin-top:12px;padding:13px;border:1px solid #e2e8f0;border-radius:10px;background:#fff}.evidence-section h4{margin:0 0 10px;color:#0f172a;font-size:15px;font-weight:800}.evidence-table-shell{overflow-x:auto}.evidence-table{width:100%;min-width:680px;border-collapse:collapse}.evidence-table th{padding:9px 10px;border-bottom:1px solid #e2e8f0;background:#f8fafc;color:#475569;font-size:12px;font-weight:800;text-align:left}.evidence-table td{padding:9px 10px;border-bottom:1px solid #eef2f7;color:#334155;font-size:13px}.evidence-note{padding:11px 12px;border-radius:9px;background:#fffbeb;color:#78350f;font-size:13px;line-height:1.55}.evidence-proposed{display:grid;grid-template-columns:1fr 1fr;gap:10px}.evidence-proposed .evidence-card{background:#ecfdf5;border-color:#a7f3d0}.evidence-review{margin-top:12px;color:#64748b;font-size:12px;font-weight:700}@media(max-width:700px){.approval-evidence{padding:14px}.approval-evidence-head{flex-direction:column}.evidence-grid,.evidence-proposed{grid-template-columns:1fr}}
</style>
<div class="approval-evidence">
    <div class="approval-evidence-head"><div><h3>Receipt Modification Evidence</h3><p>Request #<?php echo (int)($request['request_id']??0); ?> · <?php echo html_escape(ucfirst($request['request_type']??'edit')); ?> · <?php echo !empty($request['requested_at'])?html_escape(date('d M Y, H:i',(int)$request['requested_at'])):'—'; ?></p></div><span class="evidence-status <?php echo html_escape($status); ?>"><?php echo html_escape($status); ?></span></div>
    <div class="evidence-grid">
        <div class="evidence-card"><div class="evidence-label">Receipt</div><div class="evidence-value">#<?php echo html_escape((string)($request['receipt_code']??'')); ?></div></div>
        <div class="evidence-card"><div class="evidence-label">Student</div><div class="evidence-value"><?php echo html_escape($student['name']??'N/A'); ?></div><div style="color:#64748b;font-size:12px"><?php echo html_escape($student['student_code']??''); ?></div></div>
        <div class="evidence-card"><div class="evidence-label">Class</div><div class="evidence-value"><?php echo html_escape(trim(($class['name']??'').' '.($class['name_numeric']??'').' '.($section['name']??''))); ?></div></div>
        <div class="evidence-card"><div class="evidence-label">Original Total</div><div class="evidence-value"><?php echo $currency.' '.number_format($total_amount,2); ?></div></div>
        <div class="evidence-card"><div class="evidence-label">Requested By</div><div class="evidence-value"><?php echo html_escape($requester['name']??'N/A'); ?></div></div>
        <div class="evidence-card"><div class="evidence-label">Payment Method</div><div class="evidence-value"><?php $m=$payment['payment_method']??'';echo html_escape($method_map[$m]??ucfirst((string)$m)); ?></div></div>
    </div>
    <?php if(trim((string)($request['reason']??''))!==''): ?><div class="evidence-section"><h4>Reason for Modification</h4><div class="evidence-note"><?php echo nl2br(html_escape($request['reason'])); ?></div></div><?php endif; ?>
    <div class="evidence-section"><h4>Original Receipt Allocation</h4><div class="evidence-table-shell"><table class="evidence-table"><thead><tr><th>Invoice</th><th>Item</th><th>Amount</th><th>Method</th></tr></thead><tbody><?php if(!$payments): ?><tr><td colspan="4">No original payment snapshot available.</td></tr><?php else: foreach($payments as $p): ?><tr><td>#<?php echo html_escape((string)($p['invoice_code']??'')); ?></td><td><?php echo html_escape($p['title']??''); ?></td><td><?php echo $currency.' '.number_format((float)($p['amount']??0),2); ?></td><td><?php $pm=$p['payment_method']??'';echo html_escape($method_map[$pm]??ucfirst((string)$pm)); ?></td></tr><?php endforeach; endif; ?></tbody></table></div></div>
    <?php if(($request['request_type']??'')==='edit' && $new_data): ?><div class="evidence-section"><h4>Proposed Values</h4><div class="evidence-proposed"><div class="evidence-card"><div class="evidence-label">Proposed Amount</div><div class="evidence-value"><?php echo $currency.' '.number_format((float)($new_data['amount']??$total_amount),2); ?></div></div><div class="evidence-card"><div class="evidence-label">Proposed Method</div><div class="evidence-value"><?php $nm=$new_data['payment_method']??($payment['payment_method']??'');echo html_escape($method_map[$nm]??ucfirst((string)$nm)); ?></div></div></div></div><?php endif; ?>
    <?php if($status!=='pending' && $status!=='processing'): ?><div class="evidence-review">Decision: <?php echo html_escape(ucfirst($status)); ?><?php if($reviewer): ?> by <?php echo html_escape($reviewer['name']); ?><?php endif; ?><?php if(!empty($request['approved_at'])): ?> · <?php echo html_escape(date('d M Y, H:i',(int)$request['approved_at'])); ?><?php endif; ?></div><?php endif; ?>
</div>
