<?php
defined('BASEPATH') OR exit('No direct script access allowed');

class Finance_cron_model extends CI_Model {

    public function generate_admin_report() {
        $year = get_settings('running_year');
        $term = get_settings('running_term');
        $month = date('F Y');
        $currency = get_settings('currency');
        
        // Get monthly statistics
        $stats = $this->get_monthly_stats($year, $term);
        
        $html = "
        <html>
        <head>
            <style>
                body { font-family: Arial, sans-serif; }
                .header { background: #007bff; color: white; padding: 20px; text-align: center; }
                .section { margin: 20px 0; }
                .stat-box { display: inline-block; width: 30%; padding: 15px; margin: 5px; background: #f8f9fa; border-left: 4px solid #007bff; }
                table { width: 100%; border-collapse: collapse; margin: 20px 0; }
                th, td { padding: 10px; text-align: left; border-bottom: 1px solid #ddd; }
                th { background: #007bff; color: white; }
                .footer { margin-top: 30px; padding: 20px; background: #f8f9fa; text-align: center; font-size: 12px; }
            </style>
        </head>
        <body>
            <div class='header'>
                <h1>Monthly Financial Report</h1>
                <p>{$month}</p>
            </div>
            
            <div class='section'>
                <h2>Summary</h2>
                <div class='stat-box'>
                    <h3>{$currency}" . number_format($stats['total_collected'], 2) . "</h3>
                    <p>Total Collected</p>
                </div>
                <div class='stat-box'>
                    <h3>{$currency}" . number_format($stats['total_outstanding'], 2) . "</h3>
                    <p>Outstanding</p>
                </div>
                <div class='stat-box'>
                    <h3>" . $stats['collection_rate'] . "%</h3>
                    <p>Collection Rate</p>
                </div>
            </div>
            
            <div class='section'>
                <h2>Top Performing Classes</h2>
                <table>
                    <tr>
                        <th>Class</th>
                        <th>Collection Rate</th>
                        <th>Amount Collected</th>
                    </tr>";
        
        foreach ($stats['top_classes'] as $class) {
            $html .= "
                    <tr>
                        <td>{$class['class_name']}</td>
                        <td>{$class['collection_rate']}%</td>
                        <td>{$currency}" . number_format($class['collected'], 2) . "</td>
                    </tr>";
        }
        
        $html .= "
                </table>
            </div>
            
            <div class='section'>
                <h2>Payment Methods Breakdown</h2>
                <table>
                    <tr>
                        <th>Method</th>
                        <th>Transactions</th>
                        <th>Amount</th>
                    </tr>";
        
        foreach ($stats['payment_methods'] as $method) {
            $html .= "
                    <tr>
                        <td>" . strtoupper($method['payment_method']) . "</td>
                        <td>{$method['count']}</td>
                        <td>{$currency}" . number_format($method['amount'], 2) . "</td>
                    </tr>";
        }
        
        $html .= "
                </table>
            </div>
            
            <div class='footer'>
                <p>This is an automated report generated by " . get_settings('system_name') . "</p>
                <p>Generated on: " . date('Y-m-d H:i:s') . "</p>
            </div>
        </body>
        </html>";
        
        return $html;
    }

    private function get_monthly_stats($year, $term) {
        $month = date('Y-m');
        
        // Total collected
        $collected = $this->db->select_sum('amount')
            ->where('year', $year)
            ->where('term', $term)
            ->where('DATE_FORMAT(FROM_UNIXTIME(day_timestamp), "%Y-%m")', $month)
            ->get('payment')->row()->amount ?? 0;
        
        // Total outstanding
        $outstanding = $this->db->select_sum('due')
            ->where('year', $year)
            ->where('term', $term)
            ->where('status', 'due')
            ->get('invoice')->row()->due ?? 0;
        
        // Collection rate
        $total_billed = $this->db->select_sum('amount')
            ->where('year', $year)
            ->where('term', $term)
            ->get('invoice')->row()->amount ?? 1;
        
        $collection_rate = round(($collected / $total_billed) * 100, 2);
        
        // Top classes
        $top_classes = $this->db->query("
            SELECT 
                c.name as class_name,
                SUM(p.amount) as collected,
                ROUND((SUM(p.amount) / SUM(i.amount)) * 100, 2) as collection_rate
            FROM payment p
            JOIN invoice i ON p.invoice_code = i.invoice_code
            JOIN student s ON p.student_id = s.student_id
            JOIN enroll e ON s.student_id = e.student_id
            JOIN class c ON e.class_id = c.class_id
            WHERE p.year = ? AND p.term = ?
            AND DATE_FORMAT(FROM_UNIXTIME(p.day_timestamp), '%Y-%m') = ?
            GROUP BY c.class_id
            ORDER BY collection_rate DESC
            LIMIT 5
        ", [$year, $term, $month])->result_array();
        
        // Payment methods
        $payment_methods = $this->db->select('payment_method, COUNT(*) as count, SUM(amount) as amount')
            ->where('year', $year)
            ->where('term', $term)
            ->where('DATE_FORMAT(FROM_UNIXTIME(day_timestamp), "%Y-%m")', $month)
            ->group_by('payment_method')
            ->get('payment')->result_array();
        
        return [
            'total_collected' => $collected,
            'total_outstanding' => $outstanding,
            'collection_rate' => $collection_rate,
            'top_classes' => $top_classes,
            'payment_methods' => $payment_methods
        ];
    }
}
